### PR TITLE
Update shoppingcart_products.yaml

### PR DESCRIPTION
**Pull request by mikegcox**
Add fields to blueprint to add Collection header

### CODE REVIEW

**Comment by carlu93** [comment]
That's an important and necessary change. Especially for the non-technical people!

**Comment by mikegcox** [comment]
header.category is also missing.  I will do another edit

**Comment by flaviocopes** [comment]
Thanks Mike. Still miss more blueprint configuration in pages, in the plans

**Comment by mikegcox** [comment]
I will submit what I see.  I have been doing another cart

Sent from my BlackBerry - the most secure mobile device - via the Bell Network

**Pull request merged**
