### PR TITLE
:fr: final

### PR DESCRIPTION
**Pull request by MATsxm**
:fr: final
_NOTE:_ no value for the key: `SUBCATEGORIES_HEADING:` on line 79

### CODE REVIEW

**Comment by flaviocopes** [comment]
Thanks! Yes, that string is unused currently, will remove it. 

Currently working on version 2.0 which will reuse those strings for the frontend, and in addition it will provide admin-side configuration options, to make it way easier to configure the shop, so going to add a few more strings. Not immediately, it will take some time, just wanted to inform :)

**Comment by MATsxm** [comment]
:+1:  GREAT!
just ping me if I don't see them by my own.

**Comment by flaviocopes** [comment]
Also opened a dedicated Gitter channel, for easier updates notifications https://gitter.im/flaviocopes/grav-plugin-shoppingcart

**Comment by MATsxm** [comment]
TBH, I would prefere the "Translation Group" to be run the way it should be :confused: 
Anyway, thanks for the great job.

**Comment by flaviocopes** [comment]
You mean to add it to Crowdin too? Or is this talking Grav in general? PM me in case

**Pull request merged**
